name: build&test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup JDK 1.11 fox x64 architecture
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          architecture: x64
      - name: Build&Test with Maven
        run: mvn -B verify --file pom.xml